[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "BPjq2ueaJsrjSse416hh9wx6981B4EAvGHvp5cqxSKyP"
simple_file_structure = "5GpzEvVJhjy16i1rr6EotK3gMy86zPw1xvtWfyxQuv7g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
