[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock = "A2YnRqimpYk7KkW67ffMoNQtE9X3wLZJC8BcdYxbj3Sh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
